language: go
sudo: false
go:
- 1.10.x
before_install:
- go get github.com/golang/lint/golint
- go get honnef.co/go/tools/cmd/staticcheck
jobs:
  include:
  - script: make all
  - stage: Run Test Coverage
    script: make cover
    after_success: bash <(curl -s https://codecov.io/bash)
  - stage: Build Release
    script:
    - make release
    - echo "Deploying to GitHub releases ..."
    deploy:
      provider: releases
      file:
      - builds/ghlatest-darwin-amd64
      - builds/ghlatest-darwin-amd64.md5
      - builds/ghlatest-darwin-amd64.sha256
      - builds/ghlatest-freebsd-amd64
      - builds/ghlatest-freebsd-amd64.md5
      - builds/ghlatest-freebsd-amd64.sha256
      - builds/ghlatest-freebsd-386
      - builds/ghlatest-freebsd-386.md5
      - builds/ghlatest-freebsd-386.sha256
      - builds/ghlatest-linux-arm
      - builds/ghlatest-linux-arm.md5
      - builds/ghlatest-linux-arm.sha256
      - builds/ghlatest-linux-arm64
      - builds/ghlatest-linux-arm64.md5
      - builds/ghlatest-linux-arm64.sha256
      - builds/ghlatest-linux-amd64
      - builds/ghlatest-linux-amd64.md5
      - builds/ghlatest-linux-amd64.sha256
      - builds/ghlatest-linux-386
      - builds/ghlatest-linux-386.md5
      - builds/ghlatest-linux-386.sha256
      - builds/ghlatest-windows-amd64
      - builds/ghlatest-windows-amd64.md5
      - builds/ghlatest-windows-amd64.sha256
      skip_cleanup: true
      on:
        tags: true
      api_key:
        secure: wEXO6LIL55/mJOmtUpry63I+3JUxo/MvMOTeKghX2nhfOVOA8ctsAPHtCxkkNpHBopOOG2455OFME0DoGqykk5IAm1fnmsKExahXYDzCnHjfyxG6XDznkEg4hbgVJSQjd4PL7KlzL7RjQqKfttvB/0pnv7f0YWk7ysus97Px5sk3tQ7BSeZvCyPVeugP/WOtEL8NdzMQi5szrI8ZO0dRZWFFflEwgZaORC+bZoEd7ei3iWY3qdr5ri/lslD9H1KPQ8r+55Q5xC/hlQN6pYazHi4bnmRUJut1aMKJRWRRg7vlysTepcpTnWYcretJTuHMLMVurCtRx6awVgky4GWNAyqb5iw6S45hdbczN8VYsWG9qZkONnJV1/5RHZQIhy1HixTU6KMy2kRtVKVSzG3wtPQhAHcR2fVNf7Gcqa/wKonqrL89k8fjO7Z4BdlQ90BRqnuRkYAlRRxMmS3MbCzdXzvKPM9I8lzj4zhk+Me1QZepNB+yNuWYfgxDcT7k6Y8H7PfkQR4BJWAUimHbGrwdonitFP4gda33R6qOUvwg7khu9Fat6StGbs5kT9eirxN1S0ZPdUbCt0QfSnYZ6Dx/baOjdxLs/Rwn/LgCh6YMOSN5IaXfmpNq7WOqYrT6naLN8yGbl/hfh/O41RFNQWDlSlLAlt6rNaVrx1+KwbwaqmU=
